Repository SovereignCloudStack/contributor-guide, pull requests merged in 2020-08, with the labels that each got.

#7 Prologue added and reference to OpenStack guides
  source/index.rst
Labels: Type: Documentation

#8 Add license note
  source/index.rst
Labels: Type: Documentation

#9 Add dco + licenses section
  source/dco-and-licenses.rst
  source/images/github-failed-dco.png
  source/index.rst
Labels: Type: Documentation

#10 Configure renovate
  .github/pr-labeler.yml
  .github/renovate.json
Labels: Type: CI

#13 Fix license
  source/dco-and-licenses.rst
Labels: Type: Bugfix

#15 Add meeting section
  source/index.rst
  source/meetings.rst
  source/meetings/videoconference.rst
Labels: Type: Feature

#16 Add first set of meetings
  source/meetings.rst
Labels: Type: Feature

#17 Mention jitsi
  source/meetings/videoconference.rst
Labels: Type: Feature

#18 Add teams section
  source/index.rst
  source/teams.rst
Labels: Type: Feature

#19 Add glossary section
  source/glossary.rst
  source/index.rst
Labels: Type: Feature

#22 Add discussion and option for weak copyleft.
  source/license-considerations.rst
Labels: Type: Feature

#23 Add Makefile.
  Makefile
Labels: Type: Feature
